---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aeron-io-sample-backup
  namespace: aeron-io-sample-backup
  labels:
    app.kubernetes.io/name: aeron-io-sample-backup
    app.kubernetes.io/instance: aeron-io-sample-backup
...
