---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aeron-io-sample-admin
  namespace: aeron-io-sample-admin
  labels:
    app.kubernetes.io/name: aeron-io-sample-admin
    app.kubernetes.io/instance: aeron-io-sample-admin
...
