---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aeron-io-sample-admin
  namespace: aeron-io-sample-admin
  labels:
    app.kubernetes.io/name: aeron-io-sample-admin
    app.kubernetes.io/instance: aeron-io-sample-admin
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: aeron-io-sample-admin
      app.kubernetes.io/instance: aeron-io-sample-admin
  template:
    metadata:
      annotations:
        {}
      labels:
        app.kubernetes.io/name: aeron-io-sample-admin
        app.kubernetes.io/instance: aeron-io-sample-admin
    spec:
      serviceAccountName: aeron-io-sample-admin
      containers:
        - name: aeron-io-sample-admin
          image: "admin:latest"
          imagePullPolicy: IfNotPresent
          ports:
            - name: aeron
              containerPort: 49152
              protocol: UDP