---
apiVersion: v1
kind: Service
metadata:
  name: aeron-io-sample-admin
  namespace: aeron-io-sample-admin
  labels:
    app.kubernetes.io/name: aeron-io-sample-admin
    app.kubernetes.io/instance: aeron-io-sample-admin
spec:
  type: ClusterIP
  ports:
    - name: aeron
      port: 49152
      protocol: UDP
      targetPort: 49152
  selector:
    app.kubernetes.io/name: aeron-io-sample-admin
    app.kubernetes.io/instance: aeron-io-sample-admin
