/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package aeron.io.samples.app;

import aeron.io.samples.list.LinkedList;

import static aeron.io.samples.utilities.StringUtils.join;
import static aeron.io.samples.utilities.StringUtils.split;
import static aeron.io.samples.app.MessageUtils.getMessage;

import org.apache.commons.text.WordUtils;

public class App {
    public static void main(String[] args) {
        LinkedList tokens;
        tokens = split(getMessage());
        String result = join(tokens);
        System.out.println(WordUtils.capitalize(result));
    }
}
