---
apiVersion: v1
kind: Service
metadata:
  name: aeron-io-sample
  namespace: aeron-io-sample
  labels:
    app.kubernetes.io/name: aeron-io-sample
    app.kubernetes.io/instance: aeron-io-sample
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app.kubernetes.io/name: aeron-io-sample
    app.kubernetes.io/instance: aeron-io-sample
